spring:
  config:
    import: env.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB.URL:localhost}:3306/${DB.NAME:merried}
    username: ${DB.USERNAME:root}
    password: ${DB.PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: ${DB.DDL:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  data:
    redis:
      host: ${REDIS.HOST:localhost}
      port: ${REDIS.PORT:6379}
      password: ${REDIS.PASSWORD}

jwt:
  access-time: 3600000 # 1시간
  refresh-time: 2592000000 # 30일
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT.SECRET}

auth:
  kakao:
    base-url: ${KAKAO.BASE.URL}
    client-id: ${KAKAO.CLIENT}
    javascript-id: ${KAKAO.JAVASCRIPT}
    redirect-url: ${KAKAO.REDIRECT}
  naver:
    base-url: ${NAVER.BASE.URL}
    client-id: ${NAVER.CLIENT}
    secret-id: ${NAVER.SECRET}
    redirect-url: ${NAVER.REDIRECT}
    state: ${NAVER.STATE}
