spring:
  config:
    import: env.yaml
  data:
    mongodb:
      uri: ${MONGO.URL:mongodb://localhost:27017/married}
      auto-index-creation: true
    redis:
      host: ${REDIS.HOST:localhost}
      port: ${REDIS.PORT:6379}
      password: ${REDIS.PASSWORD}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  access-time: 3600000 # 1시간
  refresh-time: 2592000000 # 30일
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT.SECRET}

auth:
  kakao:
    base-url: ${KAKAO.BASE.URL}
    client-id: ${KAKAO.CLIENT}
    javascript-id: ${KAKAO.JAVASCRIPT}
    redirect-url: ${KAKAO.REDIRECT}
  naver:
    base-url: ${NAVER.BASE.URL}
    client-id: ${NAVER.CLIENT}
    secret-id: ${NAVER.SECRET}
    redirect-url: ${NAVER.REDIRECT}
    state: ${NAVER.STATE}
